---
- name: Changer le mot de passe root avec un mot de passe aléatoire
  hosts: all
  become: true
  gather_facts: false

  vars:
    password_file: "./passwords.txt"

  tasks:
    - name: Générer un mot de passe aléatoire
      set_fact:
        new_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"

    - name: Chiffrer le mot de passe pour /etc/shadow
      ansible.builtin.set_fact:
        hashed_password: "{{ new_password | password_hash('sha512') }}"

    - name: Appliquer le mot de passe root
      ansible.builtin.user:
        name: root
        password: "{{ hashed_password }}"

    - name: Ajouter l’entrée au fichier de sortie
      delegate_to: localhost
      run_once: false
      lineinfile:
        path: "{{ password_file }}"
        create: yes
        line: "{{ inventory_hostname }} : {{ new_password }}"
